name:                gd-blueprints
version:             0.1.0.0
github:              "jean-lopes/gd-blueprints"
license:             BSD3
author:              "Jean Lopes"
maintainer:          ""
copyright:           "2021 Jean Lopes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Synchronize blacksmith blueprints from hardcore and softcore

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jean-lopes/gd-blueprints#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- transformers
- containers

executables:
  gd-blueprints:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
